services:
  app:
    build:
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
    environment:
      - DATABASE_URL=${DATABASE_DOCKER_URL}
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    # volumes:
    # - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
