services:
  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    networks:
      - my-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  app:
    build:
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '3000:80'
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
